from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, Alignment
from pathlib import Path

out=Path('/Users/putra/Documents/PROJECTS/DM/duniameutya_exact_14_posts_comments.xlsx')
posts=[
('01_Rumah_Digital','DbemzciRYbI','Program rumah rakyat + konektivitas digital',[
'rumah layak jaman sekarang harus ada internet aman jg yaa 🙏','semoga akses internetnya bener2 sampai ke rumah rakyat, bukan kota besar aja','rumah nyaman, koneksi lancar... anak2 bisa belajar lebih tenang','bagus bgt pembangunan fisik dan digital jalan bareng','internet bukan lagi kemewahan, udah jadi kebutuhan sehari2','semoga jaringan cepatnya bukan cuma ada di peresmian aja 😅','buibu pasti relate, sekolah online tanpa internet stabil bikin pusing','rumah rakyat + akses digital = peluang usaha makin terbuka 🔥','semoga harganya jg terjangkau ya bu, koneksi ada tapi mahal percuma','keren... dari rumah bisa belajar, kerja, usaha dan akses layanan publik','jangan lupa keamanan digital keluarga jg perlu diedukasi','semoga daerah terpencil dapat perhatian yg sama','pembangunan masa kini bukan cuma tembok dan atap, koneksi jg penting','program bagus, semoga tepat sasaran dan terus dikawal','rumah layak, internet aman, masa depan anak lebih terbuka 🇮🇩']),
('02_Rapat_Komdigi','DbfdslJkXEM','Rapat internal dan penguatan koordinasi',[
'semangat ibu... koordinasi kuat eksekusi jg makin lancar 🙏','rapat boleh serius, yg penting hasilnya kerasa buat masyarakat','semoga semua agenda strategis bisa jalan satu2 dan tepat sasaran','Komdigi termasuk kementerian yg keliatan aktif... lanjut terus bu','keren kalau koordinasi internalnya terbuka begini, jadi publik tau prosesnya','jangan cuma rapat ya bu, ditunggu aksi nyatanya 😄','semoga tindak lanjutnya cepat, jangan berhenti di notulen','sehat selalu bu menteri, lancar semua urusannya','koordinasi yg baik biasanya hasil kerja jg lebih maksimal','semoga programnya sampai ke lapisan paling bawah','boleh dong sesekali share capaian lengkapnya bu, biar kami ikut ngintip 😅','semangat terus... kerja pemerintah memang butuh kolaborasi banyak pihak','rapatnya solid, eksekusinya jgn kalah solid yaa','semoga kebijakan digital makin bermanfaat buat rakyat','mantap bu, jaga kesehatan di tengah agenda yg padat ❤️']),
('03_Jalan_Bandung','Dbf_L9RNUm0','Jalan kaki 10 ribu langkah di Bandung',[
'Bandung emang enak buat jalan kaki malem... adem2 gimana gitu 😍','jalan kaki sambil quality time sama anak, sederhana tapi berkesan','10 ribu langkah bukan cuma sehat, pikiran jg ikut fresh','ibu cantik banget... sehat2 terus yaa 🙏','recharge yg sebenarnya buat seorang ibu wkwk','kadang memang perlu pelan2, ga harus selalu buru2','semoga makin banyak ruang publik yg nyaman buat jalan kaki','anaknya pasti seneng bisa jalan bareng ibunya','weekend sederhana tapi kenangannya bisa lama','Bandung vibesnya dapet bgt... jadi pengen jalan juga','profesional bukan berarti lupa keluarga, keren bu','sehat badan, tenang pikiran, hati senang ❤️','jalan kaki malam di Bandung memang punya suasana sendiri','semoga selalu ada waktu menikmati momen kecil begini','happy weekend bu... semoga sehat dan bahagia selalu']),
('04_Golkar_Sumsel','DbimJeXmqBx','Musda XI DPD Golkar Sumatera Selatan',[
'selamat datang di Sumsel bu... jangan lupo ngirup cuko 😄','semoga Musda berjalan lancar dan menghasilkan keputusan terbaik','Golkar Sumsel menyala 🔥 semoga makin solid','kunjungan dan silaturahmi seperti ini penting untuk konsolidasi','semoga programnya makin dekat dengan kebutuhan masyarakat Sumsel','mantap bu menteri, sehat dan sukses selalu','semoga kader2 terus kompak dan bekerja untuk rakyat','Palembang siap menyambut... pempeknya jangan lupa bu 😁','konsolidasi kuat, kerja nyata makin cepat','semoga Musda menghasilkan pemimpin yg amanah dan visioner','sukses terus untuk Golkar Sumsel 💛','jangan cuma solid di acara, solid jg dalam pelayanan masyarakat','semoga kolaborasi pusat dan daerah makin kuat','selamat bermusyawarah, semoga hasilnya membawa manfaat','mantap... semangat membangun daerah terus dijaga 🙏']),
('05_Perlindungan_Anak','DbkOnWXRq3i','Perlindungan anak dari promosi vape di platform digital',[
'anak2 memang harus dilindungi dari promosi produk berisiko... setuju bgt','good move bu, urusan anak emang harus tegas 🙏','platform jangan cuma ngejar views, keselamatan anak jg penting','buibu pasti khawatir kalau konten begini muncul di depan anak','semoga YouTube gercep memperbaiki moderasinya','anak bukan alat promosi produk, jelas banget pesannya','orang tua, kreator dan platform harus sama2 bertanggung jawab','jangan tunggu viral dulu baru ditindak yaa','aturan usia dan deteksi konten harus bener2 jalan','ruang digital aman itu hak anak2 kita','bagus langkahnya... lanjutkan pengawasan ke platform lain juga','konten anak harus edukatif, bukan diarahkan ke produk berbahaya','semoga mekanisme lapornya makin cepat dan mudah','tegas tapi tetap edukatif, ini yg dibutuhkan','anak2 kita perlu internet yg aman dan sehat 🙏']),
('06_Komunikasi_Publik','Dbk1LgVR4SW','Komunikasi publik dan tata kelola digital',[
'komunikasi pemerintah yg jelas bikin masyarakat ga gampang salah paham','semoga informasi publik makin cepat, simpel dan mudah dipahami','di era medsos, klarifikasi cepat itu penting bgt','jangan cuma aktif saat ada masalah yaa, komunikasi rutin jg perlu','masyarakat butuh info yg jelas, bukan bahasa yg muter2','semoga kanal resminya responsif menjawab pertanyaan warga','bagus kalau publik diajak ikut memahami proses kebijakan','informasi akurat bisa cegah hoaks dan provokasi','buibu juga butuh info digital yg praktis dan gampang dipahami 😅','keterbukaan dan pelayanan harus jalan bareng','semoga sampai ke daerah2, bukan pusat aja','komunikasi dua arah bikin pemerintah lebih dekat dengan rakyat','konten edukasi begini perlu diperbanyak','semoga kerja nyatanya makin terasa di kehidupan sehari2','mantap bu, terus jaga kepercayaan publik 🙏']),
('07_Perlindungan_Publik','DblCLRWE_fc','Perlindungan publik di ruang digital',[
'publik berhak merasa aman saat menggunakan teknologi','privasi itu hak, jangan dianggap sepele','semoga aturan perlindungan datanya makin kuat','konten viral bukan berarti bebas dipakai seenaknya yaa','platform jg harus ikut bertanggung jawab','ibu2 pasti lebih tenang kalau ruang digital aman buat keluarga','semoga kanal pengaduannya gampang dan cepat ditangani','teknologi maju harus dibarengi perlindungan yg kuat','jangan tunggu kasus besar baru bergerak','edukasi privasi harus dimulai dari sekolah dan keluarga','masyarakat perlu tau hak digitalnya sendiri','bagus... inovasi dan keamanan harus jalan beriringan','semoga kelompok rentan dapat perhatian lebih','perlindungan publik bukan cuma tugas pemerintah, kita semua punya peran','langkah baik, semoga konsisten dan transparan 🙏']),
('08_Dialog_Masyarakat','DblJ-KqOGhF','Dialog dan aspirasi masyarakat',[
'kalau warga diajak ngobrol, kebijakan biasanya lebih nyambung','semoga suara dari daerah jg sering didengar','dengerin masyarakat penting, follow up-nya jg jangan hilang yaa','pengalaman warga sehari2 sering jadi sumber solusi terbaik','bagus ada ruang dialog terbuka begini','masyarakat perlu tau masukannya dicatat dan ditindaklanjuti','buibu juga punya banyak cerita soal dunia digital 😄','komunikasi dua arah bikin pemerintah lebih dekat','jangan takut kritik, dari situ perbaikan bisa dimulai','semoga diskusinya rutin, bukan sekali lalu selesai','beda daerah beda kebutuhan, semoga kebijakannya fleksibel','keren... dengar dulu, pahami, baru cari solusi','semoga hasil obrolannya benar2 kembali ke masyarakat','partisipasi warga penting untuk kebijakan yg relevan','semoga makin banyak ruang aman untuk menyampaikan aspirasi 🙏']),
('09_KIP_Informasi','DbmUBwREwkB','Keterbukaan informasi publik, KIP, dan deepfake',[
'keterbukaan informasi penting bgt di zaman deepfake begini','info resmi yg cepat bisa cegah rumor berkembang kemana2','masyarakat berhak dapat informasi yg benar dan mudah diakses','semoga target indeks keterbukaan informasinya tercapai','jangan cuma dokumen yg dibuka, bahasanya jg harus mudah dipahami','buibu aja sekarang harus cek berita berkali2 sebelum share 😅','demokrasi sehat butuh informasi yg akurat','semoga layanan informasi di daerah jg makin kuat','kepercayaan publik dibangun dari data yg jelas dan konsisten','deepfake makin canggih, kanal resmi harus makin responsif','informasi publik itu hak, bukan bonus','semoga sengketa informasi bisa diselesaikan cepat dan adil','jangan sampai warga harus punya kenalan dulu baru dapat info','bagus langkahnya... keterbukaan memang fondasi demokrasi','lanjutkan penguatan layanan informasi publik 🙏']),
('10_RANA_Anak','DbpzG0ykVoJ','Gerakan ruang aman dan nyaman anak di ruang digital',[
'ruang digital aman penting bgt buat anak2 kita 🙏','buibu pasti relate, anak pegang gadget harus didampingi','semoga gerakan ini bukan cuma launching, tapi terus dikawal','orang tua jg harus belajar digital bareng anak','jangan cuma salahin anak kalau ketemu konten aneh','sekolah, keluarga, platform dan pemerintah harus jalan bareng','semoga edukasinya gampang dipahami, ga istilah teknis terus','anak berhak tumbuh dan belajar di ruang digital yg aman','konten positif anak harus diperbanyak','pencegahan lebih baik daripada menunggu anak jadi korban','semoga sampai ke daerah2 dan keluarga yg membutuhkan','keren... perlindungan anak memang tanggung jawab bersama','ibu2 perlu panduan praktis untuk mengatur aktivitas online anak','ruang digital nyaman dimulai dari kebiasaan kecil di rumah','semoga konsisten dan manfaatnya terasa di keluarga']),
('11_Hoaks_Provokasi','DbqDgSEwj-4','Hoaks, provokasi, dan persatuan',[
'bener bgt... hoaks bikin orang saling curiga dan gampang marah','jgn gampang kepancing guys, cek dulu sebelum share','berbeda pendapat boleh, saling pecah gara2 kabar palsu jangan','buibu hati2 berita dari grup WA, judulnya suka bikin panik 😅','yang paling rame belum tentu paling bener','jaga jempol, jaga persatuan 🇮🇩','hoaks sering dibuat supaya kita berantem sesama sendiri','kalau ragu simpan dulu, ga harus langsung diterusin','anak2 jg perlu diajarin bedain fakta dan provokasi','klarifikasi resmi harus cepat dan gampang ditemukan','Indonesia terlalu berharga buat dipecah informasi palsu','jangan baca judul doang terus langsung emosi 😭','ruang digital sehat dimulai dari kita sendiri','beda pilihan tetap saudara, jangan kasih hoaks ruang','semoga makin banyak yg mau cek sumber sebelum komentar 🙏']),
('12_Riset_BRIN','DbtFV4_hKjO','Riset strategis dan inovasi BRIN',[
'keren bgt... riset anak bangsa akhirnya dapet panggung di Istana','semoga hasilnya bener2 dipake masyarakat, bukan numpuk di lemari 😅','Indonesia harus mulai bikin teknologi sendiri','seneng liat sains dan inovasi dapet perhatian','riset tanpa hilirisasi sayang bgt... ditunggu hasil nyatanya','semoga UMKM jg ikut ngerasain manfaat inovasinya','anak muda jadi makin semangat masuk dunia sains','bangga liat karya anak bangsa 🇮🇩','dukungan anggaran dan kebijakan harus konsisten','dari lab menuju industri, semoga jalannya makin lancar','semoga periset mendapat fasilitas dan pendanaan berkelanjutan','karya lokal kalau didukung serius bisa mendunia','negara maju dibangun dari ilmu, bukan slogan','jangan berhenti di pameran yaa, ditunggu implementasinya','riset harus memberi dampak nyata untuk rakyat 🙏']),
('13_Bahlil_UlangTahun','DbsoddXuwhm','Ucapan ulang tahun dan perjalanan Bahlil',[
'selamat ulang tahun Pak Bahlil... sehat selalu dan makin berkah 🙏🎂','50 tahun perjalanan, semoga makin banyak karya nyata','dari Timur melangkah jauh sekali... sukses terus pak','semoga selalu amanah dan dekat dengan rakyat','fix notif Pak Bahlil penuh ucapan hari ini 😄','yang ultah sehat2, yang ngucapin ikut seneng wkwk','ditunggu gebrakan dan karya berikutnya pak','semoga keluarga selalu diberi kesehatan dan kebahagiaan','panjang umur, sehat dan lancar semua urusannya','ulang tahun baru, semangat baru, berkah baru','semoga energi positifnya terus menyala untuk negeri','keren perjalanan hidupnya, semoga menginspirasi anak muda','kuenya jangan lupa disisain yaa pak 😁','barakallah fi umrik, semoga makin amanah','selamat ulang tahun pak, sukses selalu 🔥']),
('14_Bahlil_Buku','DbudwrNkbTV','Ulang tahun Bahlil dan peluncuran buku',[
'ultah sekaligus launching buku... momennya pas bgt 🎂','semoga buku ini menginspirasi anak muda yg mulai dari nol','50 tahun perjalanan pasti penuh cerita dan pelajaran','dari Timur melangkah jauh... keren pak','ditunggu karya2 berikutnya untuk Indonesia','buku tentang karya nyata, semoga benar2 bermanfaat','selamat ulang tahun pak, sehat dan sukses terus','semoga bukunya dibaca banyak generasi muda','perjalanan hidup jadi catatan, catatan jadi inspirasi','keren... tetap berkarya dan rendah hati ya pak','barakallah fi umrik, semoga makin amanah','semoga launchingnya sukses dan bukunya laris','50 tahun bukan akhir, semoga makin banyak gebrakan','energi untuk negeri... semoga selalu full ya pak 😄','selamat ulang tahun dan selamat atas bukunya 🙏'])]

wb=Workbook(); wb.remove(wb.active)
for sheet,pid,theme,comments in posts:
    ws=wb.create_sheet(sheet)
    ws.append(['No.','Comment','Status','Used by','Notes'])
    for i,c in enumerate(comments,1): ws.append([i,c,'Belum digunakan','',''])
    ws['G1']='Post ID'; ws['H1']=pid; ws['G2']='Source URL'; ws['H2']=f'https://www.instagram.com/p/{pid}/'
    for c in ws[1]: c.font=Font(bold=True)
    ws['G1'].font=ws['G2'].font=Font(bold=True)
    ws.freeze_panes='A2'; ws.auto_filter.ref=f'A1:E{len(comments)+1}'
    for col,w in {'A':8,'B':85,'C':18,'D':20,'E':20,'G':15,'H':48}.items(): ws.column_dimensions[col].width=w
    for row in ws.iter_rows(): row[1].alignment=Alignment(wrap_text=True,vertical='top')
wb.save(out)
check=load_workbook(out,read_only=True)
assert len(check.sheetnames)==14 and all(s.max_row==16 for s in check.worksheets)
print(out); print('verified',len(check.sheetnames),'tabs x 15 comments =',len(check.sheetnames)*15)
print(check.sheetnames)

# also update the requested canonical filename
canonical=out.parent/'duniameutya_last_10_posts_comments.xlsx'
import shutil; shutil.copy2(out,canonical); print(canonical)
