[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install instaloader>=4.15.3"
]

[phases.build]
cmds = []

[start]
cmd = "python3 app.py"